#!/bin/sh
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "${POSTGRES_DB:-postgres}" <<-EOSQL
DO \$\$
BEGIN
  -- n8n
  IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname = '${POSTGRES_USER_N8N}') THEN
    CREATE ROLE ${POSTGRES_USER_N8N} LOGIN PASSWORD '${POSTGRES_PASSWORD_N8N}';
  END IF;
  IF NOT EXISTS (SELECT FROM pg_database WHERE datname = '${POSTGRES_DB_N8N}') THEN
    CREATE DATABASE ${POSTGRES_DB_N8N} OWNER ${POSTGRES_USER_N8N};
  END IF;

  -- RAG
  IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname = '${POSTGRES_USER_PGVECTOR}') THEN
    CREATE ROLE ${POSTGRES_USER_PGVECTOR} LOGIN PASSWORD '${POSTGRES_PASSWORD_PGVECTOR}';
  END IF;
  IF NOT EXISTS (SELECT FROM pg_database WHERE datname = '${POSTGRES_DB_PGVECTOR}') THEN
    CREATE DATABASE ${POSTGRES_DB_PGVECTOR} OWNER ${POSTGRES_USER_PGVECTOR};
  END IF;
END
\$\$;
EOSQL

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB_PGVECTOR" -c "CREATE EXTENSION IF NOT EXISTS vector;"

echo "Init OK: usuarios (${POSTGRES_USER_N8N}, ${POSTGRES_USER_PGVECTOR}), bancos (${POSTGRES_DB_N8N}, ${POSTGRES_DB_PGVECTOR}) e pgvector habilitado."
